"""empty message

Revision ID: f67cfd6ba8b8
Revises: 5133b7a409cf
Create Date: 2021-11-20 05:01:53.741014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67cfd6ba8b8'
down_revision = '5133b7a409cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'car_info', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_info', type_='unique')
    # ### end Alembic commands ###
